function [  ] = export_ply_segs( file, vertices, segs, col )
%EXPORT_OFF_TRI Exports a triangular mesh to a .off file
%   [  ] = export_off_tri( file, fv, col )
%
% INPUT : 
% file : out file name
% vertices : list of vertices (nx3 matrix - vertices are given by row)
% segs : list of segments given by a n_segs x 2 matrix (each row contains
%   the indices of the first/second vertex to join)
% col : color attributed to segments (vector3 of floats)

    fid = fopen(file,'w') ;
    n = size(vertices, 1) ;
    m = size(segs, 1) ;
    
    fprintf(fid, ...
        ['ply\n', ...
        'format ascii 1.0\n', ...
        'element vertex %u\n', ...
        'property float x\n', ...
        'property float y\n', ...
        'property float z\n', ...
        'property uchar red\n', ...
        'property uchar green\n', ...
        'property uchar blue\n', ...
        'element edge %u\n', ...
        'property int vertex1\n', ...
        'property int vertex2\n', ...
        'end_header\n'], ...
        n,m);
    
    for i = 1:n
        fprintf(fid, '%g %g %g %g %g %g\n', vertices(i,1), vertices(i,2), vertices(i,3),col(1)*255, col(2)*255, col(3)*255) ;
    end
    for i = 1:m
        fprintf(fid, '%d %d\n', segs(i,1)-1, segs(i,2)-1) ;
    end
    fclose(fid) ;
end

